### PR TITLE
Fix panic when running ICMPv4 probe with DontFragment

### LINKED ISSUE #685: panic when setting dont_fragment
### Host operating system: output of `uname -a`

```
Linux clara 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### blackbox_exporter version: output of `blackbox_exporter -version`

```
blackbox_exporter, version 0.17.0 (branch: master, revision: 7913a15d3c1b225f7427e9240c63ab5075281845)
  build user:       marcelo@clara
  build date:       20200827-17:06:30
  go version:       go1.14.7
```

### What is the blackbox.yml module config.

```
modules:
  ping_df:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      dont_fragment: true
  ping_f:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      dont_fragment: false
```

### What is the prometheus.yml scrape config.

none

### What logging output did you get from adding `&debug=true` to the probe URL?

none, BBE crashes.

### What did you do that produced an error?

```
$ make
$ sudo setcap cap_net_raw+ep ./blackbox_exporter
$ getcap ./blackbox_exporter
./blackbox_exporter = cap_net_raw+ep

### request http://localhost:9115/probe?target=localhost&module=ping_df&debug=true

$ ./blackbox_exporter --config.file=config.yml --log.level=debug
level=info ts=2020-08-27T17:10:23.860Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.17.0, branch=master, revision=7913a15d3c1b225f7427e9240c63ab5075281845)"
level=info ts=2020-08-27T17:10:23.860Z caller=main.go:213 msg="Build context" (gogo1.14.7,usermarcelo@clara,date20200827-17:06:30)=(MISSING)
level=info ts=2020-08-27T17:10:23.860Z caller=main.go:225 msg="Loaded config file"
level=debug ts=2020-08-27T17:10:23.860Z caller=main.go:233 externalURL=http://clara:9115
level=debug ts=2020-08-27T17:10:23.860Z caller=main.go:247 routePrefix=/
level=info ts=2020-08-27T17:10:23.860Z caller=main.go:369 msg="Listening on address" address=:9115
ts=2020-08-27T17:10:41.197Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T17:10:41.197Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-08-27T17:10:41.197Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Resolved target address" ip=127.0.0.1
ts=2020-08-27T17:10:41.197Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Creating socket"
2020/08/27 11:10:41 http: panic serving [::1]:60312: interface conversion: *icmp.PacketConn is not net.Conn: missing method Read
goroutine 49 [running]:
net/http.(*conn).serve.func1(0xc000211d60)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:1800 +0x139
panic(0xaa8ca0, 0xc00030abd0)
        /home/marcelo/devel/go/go-1.14/src/runtime/panic.go:975 +0x3e3
golang.org/x/net/ipv4.NewRawConn(0xc77fc0, 0xc0003446c0, 0xc000308530, 0x7, 0xc0003446c0)
        /home/marcelo/devel/grafana/blackbox_exporter/vendor/golang.org/x/net/ipv4/endpoint.go:169 +0x45
github.com/prometheus/blackbox_exporter/prober.ProbeICMP(0xc70860, 0xc000310060, 0xc000316012, 0x9, 0xc000035760, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /home/marcelo/devel/grafana/blackbox_exporter/prober/icmp.go:164 +0x1f7c
main.probeHandler(0xc6eda0, 0xc00032a000, 0xc000314000, 0xc00000e328, 0xc63a60, 0xc000227140, 0xc000094c80)
        /home/marcelo/devel/grafana/blackbox_exporter/main.go:119 +0x977
main.run.func4(0xc6eda0, 0xc00032a000, 0xc000314000)
        /home/marcelo/devel/grafana/blackbox_exporter/main.go:304 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc00000dc00, 0xc6eda0, 0xc00032a000, 0xc000314000)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0x113e5a0, 0xc6eda0, 0xc00032a000, 0xc000314000)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000262000, 0xc6eda0, 0xc00032a000, 0xc000314000)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000211d60, 0xc707e0, 0xc00030c000)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2962 +0x35c
ts=2020-08-27T17:10:41.197Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T17:10:41.197Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-08-27T17:10:41.198Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Resolved target address" ip=127.0.0.1
ts=2020-08-27T17:10:41.198Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Creating socket"
2020/08/27 11:10:41 http: panic serving [::1]:60314: interface conversion: *icmp.PacketConn is not net.Conn: missing method Read
goroutine 50 [running]:                                                                                                                                                                [1/9380]
net/http.(*conn).serve.func1(0xc000211e00)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:1800 +0x139
panic(0xaa8ca0, 0xc00030b380)
        /home/marcelo/devel/go/go-1.14/src/runtime/panic.go:975 +0x3e3
golang.org/x/net/ipv4.NewRawConn(0xc77fc0, 0xc000344c40, 0xc0003087b0, 0x7, 0xc000344c40)
        /home/marcelo/devel/grafana/blackbox_exporter/vendor/golang.org/x/net/ipv4/endpoint.go:169 +0x45
github.com/prometheus/blackbox_exporter/prober.ProbeICMP(0xc70860, 0xc000310840, 0xc000316792, 0x9, 0xc000035760, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /home/marcelo/devel/grafana/blackbox_exporter/prober/icmp.go:164 +0x1f7c
main.probeHandler(0xc6eda0, 0xc00032a0e0, 0xc000202500, 0xc00000e328, 0xc63a60, 0xc000227140, 0xc000094c80)
        /home/marcelo/devel/grafana/blackbox_exporter/main.go:119 +0x977
main.run.func4(0xc6eda0, 0xc00032a0e0, 0xc000202500)
        /home/marcelo/devel/grafana/blackbox_exporter/main.go:304 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc00000dc00, 0xc6eda0, 0xc00032a0e0, 0xc000202500)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0x113e5a0, 0xc6eda0, 0xc00032a0e0, 0xc000202500)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000262000, 0xc6eda0, 0xc00032a0e0, 0xc000202500)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000211e00, 0xc707e0, 0xc000099600)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2962 +0x35c
ts=2020-08-27T17:10:41.198Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T17:10:41.198Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-08-27T17:10:41.198Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Resolved target address" ip=127.0.0.1
ts=2020-08-27T17:10:41.198Z caller=main.go:169 module=ping_df target=localhost level=debug msg="Creating socket"
2020/08/27 11:10:41 http: panic serving [::1]:60316: interface conversion: *icmp.PacketConn is not net.Conn: missing method Read
goroutine 81 [running]:
net/http.(*conn).serve.func1(0xc000356140)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:1800 +0x139
panic(0xaa8ca0, 0xc00027c4e0)
        /home/marcelo/devel/go/go-1.14/src/runtime/panic.go:975 +0x3e3
golang.org/x/net/ipv4.NewRawConn(0xc77fc0, 0xc00027e1a0, 0xc000035c10, 0x7, 0xc00027e1a0)
        /home/marcelo/devel/grafana/blackbox_exporter/vendor/golang.org/x/net/ipv4/endpoint.go:169 +0x45
github.com/prometheus/blackbox_exporter/prober.ProbeICMP(0xc70860, 0xc000047c80, 0xc00003abd2, 0x9, 0xc000035760, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
        /home/marcelo/devel/grafana/blackbox_exporter/prober/icmp.go:164 +0x1f7c
main.probeHandler(0xc6eda0, 0xc0002620e0, 0xc000202600, 0xc00000e328, 0xc63a60, 0xc000227140, 0xc000094c80)
        /home/marcelo/devel/grafana/blackbox_exporter/main.go:119 +0x977
main.run.func4(0xc6eda0, 0xc0002620e0, 0xc000202600)
        /home/marcelo/devel/grafana/blackbox_exporter/main.go:304 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc00000dc00, 0xc6eda0, 0xc0002620e0, 0xc000202600)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2041 +0x44
net/http.(*ServeMux).ServeHTTP(0x113e5a0, 0xc6eda0, 0xc0002620e0, 0xc000202600)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2416 +0x1a5
net/http.serverHandler.ServeHTTP(0xc000262000, 0xc6eda0, 0xc0002620e0, 0xc000202600)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc000356140, 0xc707e0, 0xc000099700)
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /home/marcelo/devel/go/go-1.14/src/net/http/server.go:2962 +0x35c
```

### What did you expect to see?

not crash

### What did you see instead?

crash

### PR DESCRIPTION
**Pull request by mem**
A recent change modified the way an IPv4 raw socket is created and BBE
is panicing when ICMPv4 is used with DontFragment set.

golang.org/x/net doesn't seem to have a way to create the necessary
socket, so fall back to the previous method for that case in particular
(ICMP, IPv4, DontFragment=true).

Fixes #685

Signed-off-by: Marcelo E. Magallon <marcelo.magallon@grafana.com>

### CODE REVIEW

**Comment by mem** [comment]
this is running this change with capabilities set:

```
ts=2020-08-27T21:35:12.024Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T21:35:12.024Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-08-27T21:35:12.025Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Resolved target address" ip=127.0.0.1
ts=2020-08-27T21:35:12.025Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Creating socket"
ts=2020-08-27T21:35:12.025Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Creating ICMP packet" seq=55056 id=31912
ts=2020-08-27T21:35:12.026Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Writing out packet"
ts=2020-08-27T21:35:12.026Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Waiting for reply packets"
ts=2020-08-27T21:35:12.026Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Found matching reply packet"
ts=2020-08-27T21:35:12.026Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Probe succeeded" duration_seconds=0.001902335
ts=2020-08-27T21:35:22.209Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T21:35:22.210Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-08-27T21:35:22.210Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Resolved target address" ip=127.0.0.1
ts=2020-08-27T21:35:22.210Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Creating socket"
ts=2020-08-27T21:35:22.210Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Creating ICMP packet" seq=55057 id=31912
ts=2020-08-27T21:35:22.210Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Writing out packet"
ts=2020-08-27T21:35:22.211Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Waiting for reply packets"
ts=2020-08-27T21:35:22.211Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Found matching reply packet"
ts=2020-08-27T21:35:22.211Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Probe succeeded" duration_seconds=0.001515964
ts=2020-08-27T21:35:32.834Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T21:35:32.834Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Resolving target address" ip_protocol=ip6
ts=2020-08-27T21:35:32.834Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Resolved target address" ip=::1
ts=2020-08-27T21:35:32.834Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Creating socket"
ts=2020-08-27T21:35:32.834Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Creating ICMP packet" seq=55058 id=31912
ts=2020-08-27T21:35:32.834Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Writing out packet"
ts=2020-08-27T21:35:32.834Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Waiting for reply packets"
ts=2020-08-27T21:35:32.835Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Found matching reply packet"
ts=2020-08-27T21:35:32.835Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Probe succeeded" duration_seconds=0.00033165
ts=2020-08-27T21:35:37.967Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T21:35:37.967Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Resolving target address" ip_protocol=ip6
ts=2020-08-27T21:35:37.967Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Resolved target address" ip=::1
ts=2020-08-27T21:35:37.968Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Creating socket"
ts=2020-08-27T21:35:37.968Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Creating ICMP packet" seq=55059 id=31912
ts=2020-08-27T21:35:37.968Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Writing out packet"
ts=2020-08-27T21:35:37.968Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Waiting for reply packets"
ts=2020-08-27T21:35:37.968Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Found matching reply packet"
ts=2020-08-27T21:35:37.968Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Probe succeeded" duration_seconds=0.000917358
```

and this is running this code without capabilities set:

```
ts=2020-08-27T21:36:31.267Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T21:36:31.267Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Resolving target address" ip_protocol=ip6
ts=2020-08-27T21:36:31.267Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Resolved target address" ip=::1
ts=2020-08-27T21:36:31.267Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Creating socket"
ts=2020-08-27T21:36:31.267Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Creating ICMP packet" seq=40949 id=36974
ts=2020-08-27T21:36:31.268Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Writing out packet"
ts=2020-08-27T21:36:31.268Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Waiting for reply packets"
ts=2020-08-27T21:36:31.268Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Found matching reply packet"
ts=2020-08-27T21:36:31.268Z caller=main.go:169 module=ping_df_v6 target=::1 level=debug msg="Probe succeeded" duration_seconds=0.000963329
ts=2020-08-27T21:36:36.964Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T21:36:36.965Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Resolving target address" ip_protocol=ip6
ts=2020-08-27T21:36:36.965Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Resolved target address" ip=::1
ts=2020-08-27T21:36:36.965Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Creating socket"
ts=2020-08-27T21:36:36.965Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Creating ICMP packet" seq=40950 id=36974
ts=2020-08-27T21:36:36.965Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Writing out packet"
ts=2020-08-27T21:36:36.966Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Waiting for reply packets"
ts=2020-08-27T21:36:36.966Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Found matching reply packet"
ts=2020-08-27T21:36:36.966Z caller=main.go:169 module=ping_f_v6 target=::1 level=debug msg="Probe succeeded" duration_seconds=0.001217941
ts=2020-08-27T21:36:52.868Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T21:36:52.868Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-08-27T21:36:52.868Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Resolved target address" ip=127.0.0.1
ts=2020-08-27T21:36:52.868Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Creating socket"
ts=2020-08-27T21:36:52.869Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Creating ICMP packet" seq=40951 id=36974
ts=2020-08-27T21:36:52.869Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Writing out packet"
ts=2020-08-27T21:36:52.869Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Waiting for reply packets"
ts=2020-08-27T21:36:52.869Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Found matching reply packet"
ts=2020-08-27T21:36:52.869Z caller=main.go:169 module=ping_f_v4 target=localhost level=debug msg="Probe succeeded" duration_seconds=0.001453394
ts=2020-08-27T21:36:57.044Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Beginning probe" probe=icmp timeout_seconds=119.5
ts=2020-08-27T21:36:57.045Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-08-27T21:36:57.045Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Resolved target address" ip=127.0.0.1
ts=2020-08-27T21:36:57.045Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Creating socket"
ts=2020-08-27T21:36:57.045Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Error listening to socket" err="listen ip4:icmp 0.0.0.0: socket: operation not permitted"
ts=2020-08-27T21:36:57.045Z caller=main.go:169 module=ping_df_v4 target=localhost level=debug msg="Probe failed" duration_seconds=0.000818169
```

the case that fails (last line) is the one that requires privileges, so the failure is expected.

**Comment by mem** [comment]
@dgl could you please take a look?

**Comment by brian-brazil** [comment]
Thanks for finding, and fixing this. This looks like the right fix to me, @dgl do you have any comments before I merge?

File: prober/icmp.go [hunk 1]
```diff
@@ -140,42 +140,48 @@ func ProbeICMP(ctx context.Context, target string, module config.Module, registr
...
-		if module.ICMP.DontFragment {
 			rc, err := ipv4.NewRawConn(icmpConn)
 			if err != nil {
 				level.Error(logger).Log("msg", "Error creating raw connection", "err", err)
 				return
 			}
 			socket = &v4Conn{c: rc, df: true}
 		} else {
+			var icmpConn *icmp.PacketConn
+			// If the user has set the don't fragment option we cannot use unprivileged
```
Comment (dgl) [inline prober/icmp.go:158]: Move comment to the other branch of the if, probably update it to say something like "Need to use RawConn rather than ICMP socket in order to set IP header level options."

**Comment by dgl** [comment]
LGTM, aside from my comment about the comment.

File: prober/icmp.go (hunk 1 above)
Comment (mem) [reply prober/icmp.go:158]: thanks, done!

**Comment by brian-brazil** [comment]
Thanks!
