### PR TITLE
Fixed timeout bug

### LINKED ISSUE #203: ssh_banner module is not working
### Host operating system: output of `uname -a`
Ubuntu 16.04.2 LTS
`Linux pc-010-242 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter -version`
Using latest Dockernized version.
```
blackbox_exporter, version 0.7.0 (branch: master, revision: 9b67dd9b488160bb656cf130718b2aa62a7f30e6)
  build user:       root@756261f4b8ec
  build date:       20170714-14:40:00
  go version:       go1.8.3
```

### What is the blackbox.yml module config.
Use default in the image.

### What is the prometheus.yml scrape config.
n/a

### What logging output did you get from the `blackbox_exporter`?
See below.

#### Server side
```
$ docker run --cap-add ALL --network host --rm -it prom/blackbox-exporter -config.file=/etc/blackbox_exporter/config.yml -log.level=debug
INFO[0000] Starting blackbox_exporter (version=0.7.0, branch=master, revision=9b67dd9b488160bb656cf130718b2aa62a7f30e6)  source="main.go:153"
INFO[0000] Build context (go=go1.8.3, user=root@756261f4b8ec, date=20170714-14:40:00)  source="main.go:154"
INFO[0000] Loaded config file                            source="main.go:71"
INFO[0000] Listening on :9115                            source="main.go:226"
DEBU[0003] Processing query response entry {Expect:^SSH-2.0- Send: XXX:map[]}  source="tcp.go:98"
```
I know `--cap-add ALL` is not required, it was added to eliminate capability-related issue.

#### Client side
HELP and TYPE lines are omitted.

```
# sshd is working and the response is valid.
$ telnet 127.0.0.1 22
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.2

# However, probe_success returns 0.
$ curl 'http://localhost:9115/probe?module=ssh_banner&target=127.0.0.1:22'
probe_dns_lookup_time_seconds 1.17e-07
probe_duration_seconds 0.000477857
probe_failed_due_to_regex 0
probe_ip_protocol 4
probe_success 0

# It also occurs on IPv6.
$ telnet ::1 22
(snip)
$ curl 'http://localhost:9115/probe?module=ssh_banner&target=localhost:22'
(snip)
probe_ip_protocol 6
probe_success 0

# Note: tcp_connect module is working.
$ curl 'http://localhost:9115/probe?module=tcp_connect&target=127.0.0.1:22'
probe_dns_lookup_time_seconds 1.06e-07
probe_duration_seconds 0.000271281
probe_failed_due_to_regex 0
probe_ip_protocol 4
probe_success 1
```

It also reproduced against other sshd including CentOS 6/7, Amazon Linux and CoreOS.

### What did you expect to see?
probe_success should be 1.

### What did you see instead?
probe_success got 0.

### PR DESCRIPTION
**Pull request by Conorbro**
Fixes #203

### CODE REVIEW

File: tcp.go [hunk 1]
```diff
@@ -114,6 +113,7 @@ func probeTCP(ctx context.Context, target string, module Module, registry *prome
 				}
 			}
 			if scanner.Err() != nil {
+				log.Errorf(scanner.Err().Error())
```
Comment (brian-brazil) [inline tcp.go]: The first parameter to Errorf is the format string, so put something in here to give the user context

File: tcp_test.go [hunk 2]
```diff
@@ -137,9 +136,8 @@ func TestTCPConnectionQueryResponseMatching(t *testing.T) {
 
 	testCTX, cancel := context.WithTimeout(context.Background(), 10*time.Second)
 	defer cancel()
-
+	time.Sleep(100)
```
Comment (brian-brazil) [inline tcp_test.go]: This is 100ns. Use time.Millisecond *10 at least.
